sudo: required
services:
  -docker

before_install:
  - docker build -t narasimhakamath/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true narasimhakamath/docker-react npm run test

deploy:
  provided: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-510273660898"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY